spring:
  application:
    name: jbone-sm-gateway
  redis:
    host: 10.251.35.116
    port: 6379
    password: jboneonline
  #rabbitmq配置
  rabbitmq:
    host: 10.251.35.116
    port: 5672
    username: admin
    password: 123456
  #
  # 以下为 zipkin客户端配置
  #
  sleuth:
    sampler:
      probability: 1
    messaging:
      enabled: true
      rabbit:
        enabled: true
  zipkin:
    sender:
      type: rabbit

zipkin.rabbitmq.queue: zipkin

# ###

server.port: 10005

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.251.35.116:10001/eureka,http://10.163.185.74:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置
zuul:
  ignoredServices: '*' # 安全起见，屏蔽所有服务，自定义暴漏服务
  routes:
    jbone-sys-server: /system/**  #暴漏jbone-sys-server的服务
    jbone-cms-server: /cms/**     #暴漏jbone-cms-server的服务
    jbone-fs-server: /fs/**       #文件上传
  sensitive-headers:

# 转发超时时间
ribbon:
  ReadTimeout: 10000  # 单位毫秒数
  SocketTimeout: 10000

#CAS服务地址
jbone:
  #系统服务名称
  sys:
    serverName: jbone-sm-gateway
    #feign通讯协议，默认http://
    serverProtoal: http://
  #系统管理Feign调用配置
  rpc.sysServer.feign:
    protocol: http
    name: jbone-sys-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.jbone.cn

# 启用超时设置
hystrix.command.default.execution.timeout.enabled: true
# 熔断时间为10S
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 使用线程隔离熔断
hystrix.command.default.execution.isolation.strategy: THREAD
# 核心线程数100
hystrix.threadpool.default.coreSize: 100
# 超时时熔断
hystrix.command.default.execution.isolation.thread.interruptOnTimeout: true
# 取消时是否熔断
hystrix.command.default.execution.isolation.thread.interruptOnCancel: false
